name: Build and Deploy Hugo Site
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write 
  id-token: write 

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2 
        with:
          hugo-version: '0.111.0'
          extended: true

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Build
        run: hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-key@v1  
        with:
          cleanup: true
          deploy-key: ${{ secrets.DEPLOY_KEY }}
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
          ssh-known-hosts: ${{ secrets.GIT_KNOWN_HOSTS }}

      - name: Publish to gh-pages (optional)
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v3
        with:
          ref: gh-pages 
          persist-credentials: false
          fetch-depth: 0
        run: |
          cp -R public/* ${HOME}/built-site  
          cd ${HOME}/built-site
          git init  
          git add .
          git config user.name 'ChetanThapliyal'
          git config user.email 'chetan_thapliyal@tuta.io'
          git commit -m 'Updated site'
          git push origin gh-pages --force
